"""A focused B1 route: 24 lessons, four modules, multilingual instruction copy."""

B1_CURRICULUM = [
    (31, 1, "subordinate_clauses", "grammar", "Nebensätze mit obwohl", "Nebensätze mit obwohl", "Subordinate clauses with obwohl", "В придаточном с obwohl глагол стоит в конце.", "Im obwohl-Satz steht das Verb am Ende.", "In an obwohl-clause, the verb goes at the end.", "Verbinde: Es regnet. Wir gehen spazieren.", "Verbinde: Es regnet. Wir gehen spazieren.", "Join the sentences: It is raining. We are going for a walk.", "Obwohl es regnet, gehen wir spazieren.", "Объясни контраст с obwohl.", "Drücke einen Gegensatz mit obwohl aus.", "Express a contrast with obwohl."),
    (32, 1, "temporal_clauses", "grammar", "Когда: als или wenn", "Als oder wenn", "When: als or wenn", "als — однократное событие в прошлом; wenn — повторение или условие.", "Als steht bei einem einmaligen Ereignis in der Vergangenheit; wenn bei Wiederholung oder Bedingung.", "Use als for a single past event and wenn for repeated events or conditions.", "___ ich klein war, wohnte ich in Köln.", "___ ich klein war, wohnte ich in Köln.", "Complete: ___ ich klein war, wohnte ich in Köln.", "Als ich klein war, wohnte ich in Köln.", "Расскажи об одном моменте в прошлом.", "Erzähle von einem Zeitpunkt in der Vergangenheit.", "Describe one moment in your past."),
    (33, 1, "indirect_questions", "grammar", "Косвенные вопросы", "Indirekte Fragen", "Indirect questions", "В косвенном вопросе глагол стоит в конце; для ja/nein используется ob.", "In indirekten Fragen steht das Verb am Ende; bei Ja/Nein-Fragen nutzt man ob.", "In indirect questions, the verb goes at the end; use ob for yes/no questions.", "Formuliere indirekt: Kommt der Zug pünktlich?", "Formuliere indirekt: Kommt der Zug pünktlich?", "Turn into an indirect question: Kommt der Zug pünktlich?", "Ich weiß nicht, ob der Zug pünktlich kommt.", "Вежливо задай косвенный вопрос.", "Stelle höflich eine indirekte Frage.", "Ask a polite indirect question."),
    (34, 1, "purpose_clauses", "grammar", "damit и um…zu", "Damit und um…zu", "damit and um…zu", "um…zu используется при одном подлежащем; damit — при разных.", "Um…zu nutzt man bei gleichem Subjekt, damit bei verschiedenen Subjekten.", "Use um…zu with the same subject and damit with different subjects.", "Ich lerne viel. Ich will die Prüfung bestehen.", "Ich lerne viel. Ich will die Prüfung bestehen.", "Combine: I study a lot. I want to pass the exam.", "Ich lerne viel, um die Prüfung zu bestehen.", "Объясни цель своего действия.", "Erkläre das Ziel einer Handlung.", "Explain the purpose of an action."),
    (35, 1, "relative_clauses", "grammar", "Относительные предложения", "Relativsätze", "Relative clauses", "Род и число относительного местоимения берутся от существительного, падеж — из придаточного.", "Genus und Numerus kommen vom Bezugswort, der Kasus aus dem Relativsatz.", "Gender and number come from the noun; case comes from the relative clause.", "Das ist der Mann. Ich helfe dem Mann.", "Das ist der Mann. Ich helfe dem Mann.", "Join: Das ist der Mann. Ich helfe dem Mann.", "Das ist der Mann, dem ich helfe.", "Опиши человека относительным предложением.", "Beschreibe eine Person mit einem Relativsatz.", "Describe a person with a relative clause."),
    (36, 1, "double_connectors", "grammar", "Двойные союзы", "Zweiteilige Konnektoren", "Paired conjunctions", "nicht nur…sondern auch добавляет информацию; entweder…oder показывает выбор.", "Nicht nur…sondern auch ergänzt; entweder…oder bietet eine Wahl.", "Nicht nur…sondern auch adds information; entweder…oder presents a choice.", "Sie spricht Deutsch. Sie spricht Englisch.", "Sie spricht Deutsch. Sie spricht Englisch.", "Combine: She speaks German. She speaks English.", "Sie spricht nicht nur Deutsch, sondern auch Englisch.", "Сравни две возможности.", "Verbinde zwei Möglichkeiten.", "Connect two possibilities."),
    (37, 2, "passive_voice", "grammar", "Passiv Präsens", "Passiv im Präsens", "Present passive", "Процесс выражается werden + Partizip II.", "Ein Vorgang wird mit werden + Partizip II ausgedrückt.", "An action is expressed with werden + past participle.", "Man repariert die Straße.", "Man repariert die Straße.", "Change to passive: Man repariert die Straße.", "Die Straße wird repariert.", "Опиши процесс без исполнителя.", "Beschreibe einen Vorgang ohne Handelnden.", "Describe a process without naming the agent."),
    (38, 2, "passive_past", "grammar", "Passiv Präteritum", "Passiv im Präteritum", "Past passive", "В прошедшем Passiv используется wurde/wurden + Partizip II.", "Im Präteritum Passiv steht wurde/wurden + Partizip II.", "The past passive uses wurde/wurden + past participle.", "Die Firma baute das Haus 1990.", "Die Firma baute das Haus 1990.", "Change to past passive: Die Firma baute das Haus 1990.", "Das Haus wurde 1990 gebaut.", "Сообщи о завершённом процессе.", "Berichte über einen vergangenen Vorgang.", "Report a completed process."),
    (39, 2, "modal_past", "grammar", "Модальные глаголы в Präteritum", "Modalverben im Präteritum", "Modal verbs in the past", "konnte, musste, durfte часто используются вместо Perfekt.", "Konnte, musste und durfte werden häufig statt Perfekt verwendet.", "Konnte, musste and durfte are often used instead of the perfect tense.", "Früher ___ ich jeden Tag trainieren. (müssen)", "Früher ___ ich jeden Tag trainieren. (müssen)", "Complete with müssen in the past.", "Früher musste ich jeden Tag trainieren.", "Расскажи о прошлой обязанности.", "Erzähle von einer früheren Pflicht.", "Describe a past obligation."),
    (40, 2, "konjunktiv_ii", "grammar", "Konjunktiv II: советы", "Konjunktiv II: Ratschläge", "Konjunktiv II: advice", "Для мягкого совета используются sollte, könnte и würde.", "Für höfliche Ratschläge nutzt man sollte, könnte und würde.", "Use sollte, könnte and würde for polite advice.", "Du bist oft müde. Gib einen Rat.", "Du bist oft müde. Gib einen Rat.", "Give advice to someone who is often tired.", "Du solltest früher schlafen gehen.", "Дай вежливый совет.", "Gib einen höflichen Rat.", "Give polite advice."),
    (41, 2, "lassen", "grammar", "lassen + Infinitiv", "Lassen + Infinitiv", "lassen + infinitive", "lassen означает поручить действие или позволить; инфинитив стоит в конце.", "Lassen bedeutet veranlassen oder erlauben; der Infinitiv steht am Ende.", "Lassen means to have something done or allow it; the infinitive goes at the end.", "Der Friseur schneidet meine Haare.", "Der Friseur schneidet meine Haare.", "Rewrite with lassen.", "Ich lasse mir die Haare schneiden.", "Скажи, что ты поручаешь сделать.", "Sage, was du machen lässt.", "Say what you have done for you."),
    (42, 2, "subjective_modals", "grammar", "Субъективные Modalverben", "Subjektive Modalverben", "Modal verbs for reported probability", "soll передаёт чужое утверждение, muss — сильное предположение.", "Sollen gibt eine fremde Aussage wieder; müssen eine starke Vermutung.", "Sollen reports a claim; müssen expresses a strong assumption.", "Man sagt, er ist sehr reich.", "Man sagt, er ist sehr reich.", "Report the claim with sollen.", "Er soll sehr reich sein.", "Передай непроверенную информацию.", "Gib eine unbestätigte Information wieder.", "Report unconfirmed information."),
    (43, 3, "adjective_declension", "grammar", "Склонение прилагательных", "Adjektivdeklination", "Adjective endings", "Окончание зависит от артикля, рода, числа и падежа.", "Die Endung hängt von Artikel, Genus, Numerus und Kasus ab.", "The ending depends on article, gender, number and case.", "Ich spreche mit einem nett___ Kollegen.", "Ich spreche mit einem nett___ Kollegen.", "Complete the adjective ending.", "Ich spreche mit einem netten Kollegen.", "Опиши человека с правильным окончанием.", "Beschreibe eine Person mit richtiger Endung.", "Describe a person with the correct ending."),
    (44, 3, "verb_prepositions", "grammar", "Глаголы с предлогами", "Verben mit Präpositionen", "Verbs with prepositions", "Предлог и падеж нужно учить вместе с глаголом.", "Präposition und Kasus lernt man zusammen mit dem Verb.", "Learn the preposition and case together with the verb.", "Ich interessiere mich ___ Politik.", "Ich interessiere mich ___ Politik.", "Complete the preposition.", "Ich interessiere mich für Politik.", "Расскажи о своём интересе.", "Sprich über ein Interesse.", "Talk about an interest."),
    (45, 3, "noun_verb_connections", "vocabulary", "Nomen-Verb-Verbindungen", "Nomen-Verb-Verbindungen", "Noun–verb collocations", "Устойчивые сочетания используются как одно смысловое целое.", "Feste Nomen-Verb-Verbindungen bilden eine Bedeutungseinheit.", "Fixed noun–verb combinations work as one meaning unit.", "Wir müssen eine Entscheidung ___.", "Wir müssen eine Entscheidung ___.", "Complete the collocation.", "Wir müssen eine Entscheidung treffen.", "Используй устойчивое сочетание в контексте.", "Nutze eine feste Verbindung im Kontext.", "Use a fixed collocation in context."),
    (46, 3, "genitive_prepositions", "grammar", "Предлоги с Genitiv", "Genitivpräpositionen", "Genitive prepositions", "wegen, trotz, während и aufgrund часто требуют Genitiv.", "Wegen, trotz, während und aufgrund stehen häufig mit Genitiv.", "Wegen, trotz, während and aufgrund often take the genitive.", "Trotz ___ schlechten Wetters gehen wir raus.", "Trotz ___ schlechten Wetters gehen wir raus.", "Complete the genitive form.", "Trotz des schlechten Wetters gehen wir raus.", "Объясни обстоятельство через Genitiv.", "Nenne einen Umstand mit Genitiv.", "Explain a circumstance using the genitive."),
    (47, 3, "pronoun_adverbs", "grammar", "Pronominaladverbien", "Pronominaladverbien", "Pronominal adverbs", "Для вещей используются daran, darauf, darüber; для людей — предлог + местоимение.", "Für Sachen nutzt man daran, darauf, darüber; für Personen Präposition + Pronomen.", "Use daran, darauf and darüber for things; use preposition + pronoun for people.", "Worauf wartest du? — Ich warte ___, dass der Kurs beginnt.", "Worauf wartest du? — Ich warte ___, dass der Kurs beginnt.", "Complete the pronominal adverb.", "Ich warte darauf, dass der Kurs beginnt.", "Скажи, чего ты ожидаешь.", "Sage, worauf du wartest.", "Say what you are waiting for."),
    (48, 3, "nominalization", "grammar", "Номинализация", "Nominalisierung", "Nominalisation", "Глагольную идею можно выразить существительным для более формального стиля.", "Eine verbale Aussage kann für formellen Stil nominalisiert werden.", "A verbal idea can be nominalised for a more formal style.", "Weil die Preise steigen, sparen viele Menschen.", "Weil die Preise steigen, sparen viele Menschen.", "Rewrite more formally with wegen.", "Wegen des Preisanstiegs sparen viele Menschen.", "Переформулируй мысль формально.", "Formuliere eine Aussage formeller.", "Rephrase an idea in a formal style."),
    (49, 4, "formal_email", "writing", "Формальное письмо", "Formelle E-Mail", "Formal email", "Письмо содержит обращение, ясную просьбу и вежливое завершение.", "Eine formelle E-Mail enthält Anrede, klares Anliegen und höflichen Schluss.", "A formal email needs a greeting, clear request and polite closing.", "Bitte um einen neuen Termin.", "Bitte um einen neuen Termin.", "Ask for a new appointment.", "Könnten Sie mir bitte einen neuen Termin anbieten?", "Напиши вежливую просьбу.", "Formuliere eine höfliche Bitte.", "Write a polite request."),
    (50, 4, "opinion", "writing", "Выражение мнения", "Eine Meinung ausdrücken", "Expressing an opinion", "Сначала сформулируй позицию, затем причину и пример.", "Nenne zuerst deine Position, dann einen Grund und ein Beispiel.", "State your position, then give a reason and an example.", "Sollte Homeoffice häufiger möglich sein?", "Sollte Homeoffice häufiger möglich sein?", "Should working from home be available more often?", "Meiner Meinung nach sollte Homeoffice häufiger möglich sein, weil es Zeit spart.", "Сформулируй мнение и причину.", "Formuliere eine Meinung mit Begründung.", "State and justify an opinion."),
    (51, 4, "argumentation", "writing", "Аргумент: плюс и минус", "Pro und Contra", "Pros and cons", "Свяжи преимущество и недостаток через einerseits…andererseits.", "Verbinde Vorteil und Nachteil mit einerseits…andererseits.", "Connect an advantage and disadvantage with einerseits…andererseits.", "Onlinekurse sind flexibel, aber oft unpersönlich.", "Onlinekurse sind flexibel, aber oft unpersönlich.", "Connect the two sides with einerseits…andererseits.", "Einerseits sind Onlinekurse flexibel, andererseits sind sie oft unpersönlich.", "Сравни преимущество и недостаток.", "Vergleiche einen Vorteil und einen Nachteil.", "Compare one advantage and one disadvantage."),
    (52, 4, "listening_attitude", "listening", "Позиция говорящего", "Haltung des Sprechers", "Speaker attitude", "Обращай внимание на zwar…aber, jedoch, vermutlich и интонацию.", "Achte auf zwar…aber, jedoch, vermutlich und die Intonation.", "Listen for zwar…aber, jedoch, vermutlich and intonation.", "Die Idee ist zwar interessant, aber kaum realistisch.", "Die Idee ist zwar interessant, aber kaum realistisch.", "What is the speaker's position?", "Der Sprecher ist skeptisch.", "Определи позицию по языковым сигналам.", "Erkenne die Haltung an sprachlichen Signalen.", "Identify attitude from language signals."),
    (53, 4, "spoken_narrative", "speaking", "Связный рассказ", "Zusammenhängend erzählen", "Connected speaking", "Структурируй рассказ маркерами zuerst, danach, schließlich.", "Strukturiere mit zuerst, danach und schließlich.", "Structure your account with zuerst, danach and schließlich.", "Erzähle von einem schwierigen Tag.", "Erzähle von einem schwierigen Tag.", "Talk about a difficult day.", "Zuerst habe ich den Bus verpasst, danach kam ich zu spät, aber schließlich hat alles geklappt.", "Расскажи историю из трёх шагов.", "Erzähle eine Geschichte in drei Schritten.", "Tell a three-step story."),
    (54, 4, "b1_final", "mixed", "B1-Abschlussaufgabe", "B1-Abschlussaufgabe", "B1 final task", "Объедини мнение, причину, пример и вывод в связный ответ.", "Verbinde Meinung, Grund, Beispiel und Schluss in einer zusammenhängenden Antwort.", "Combine an opinion, reason, example and conclusion in one coherent response.", "Ist das Leben in einer Großstadt besser?", "Ist das Leben in einer Großstadt besser?", "Is life in a large city better?", "Meiner Meinung nach bietet eine Großstadt viele Chancen, obwohl sie oft laut ist. Deshalb kommt es auf die eigenen Ziele an.", "Дай связный ответ уровня B1.", "Gib eine zusammenhängende Antwort auf B1-Niveau.", "Give a coherent B1-level response."),
]

B1_TASKS = {
    "subordinate_clauses": ("Obwohl es regnet, wir gehen spazieren.", "Друг предлагает прогулку, хотя идёт дождь. Ответь с obwohl.", "Ein Freund schlägt trotz Regen einen Spaziergang vor. Antworte mit obwohl.", "A friend suggests a walk although it is raining. Reply with obwohl.", "Gegensatz", ["Grund", "Bedingung"], "verb_not_final"),
    "temporal_clauses": ("Wenn ich klein war, wohnte ich in Köln.", "Ты рассказываешь коллеге об одном периоде детства.", "Du erzählst einem Kollegen von einer einmaligen Zeit in deiner Kindheit.", "You are telling a colleague about one period in your childhood.", "einmalige Vergangenheit", ["Wiederholung", "Bedingung"], "wrong_connector"),
    "indirect_questions": ("Ich weiß nicht, ob kommt der Zug pünktlich.", "Вежливо спроси сотрудника вокзала о поезде.", "Frage einen Bahnmitarbeiter höflich nach dem Zug.", "Politely ask a station employee about the train.", "indirekte Ja/Nein-Frage", ["direkte Frage", "Begründung"], "verb_not_final"),
    "purpose_clauses": ("Ich lerne viel, um ich die Prüfung bestehe.", "Объясни другу, зачем ты много занимаешься.", "Erkläre einem Freund, warum du viel lernst.", "Explain to a friend why you study a lot.", "Ziel bei gleichem Subjekt", ["Grund", "Gegensatz"], "wrong_connector"),
    "relative_clauses": ("Das ist der Mann, den ich helfe.", "Представь коллегу, которому ты часто помогаешь.", "Stelle den Kollegen vor, dem du oft hilfst.", "Introduce the colleague whom you often help.", "Person im Dativ", ["Person im Akkusativ", "Ort"], "relative_case"),
    "double_connectors": ("Sie spricht nicht nur Deutsch, aber auch Englisch.", "Представь кандидата с двумя языковыми навыками.", "Stelle eine Bewerberin mit zwei Sprachkenntnissen vor.", "Introduce an applicant with two language skills.", "zwei Ergänzungen", ["Alternative", "Einschränkung"], "wrong_connector"),
    "passive_voice": ("Die Straße hat repariert.", "Сообщи жителям о текущих дорожных работах.", "Informiere Anwohner über aktuelle Straßenarbeiten.", "Inform residents about current roadworks.", "Vorgang ohne Handelnden", ["Zustand", "Vermutung"], "passive_auxiliary"),
    "passive_past": ("Das Haus wird 1990 gebaut.", "Расскажи посетителю об истории здания.", "Erzähle einem Besucher von der Geschichte des Gebäudes.", "Tell a visitor about the building's history.", "vergangener Vorgang", ["aktueller Vorgang", "zukünftiger Plan"], "passive_auxiliary"),
    "modal_past": ("Früher muss ich jeden Tag trainieren.", "Расскажи о прежней обязанности.", "Erzähle von einer früheren Pflicht.", "Talk about an obligation you had in the past.", "frühere Pflicht", ["heutige Pflicht", "Erlaubnis"], "modal_form"),
    "konjunktiv_ii": ("Du sollst früher schlafen gehen.", "Друг постоянно устает. Дай ему мягкий совет.", "Ein Freund ist ständig müde. Gib einen freundlichen Rat.", "A friend is constantly tired. Give gentle advice.", "höflicher Rat", ["strenger Befehl", "Bericht"], "modal_form"),
    "lassen": ("Ich lasse der Friseur meine Haare schneiden.", "Объясни, какую услугу ты заказываешь в салоне.", "Erkläre, welche Dienstleistung du im Salon machen lässt.", "Explain which service you have done at the salon.", "Dienstleistung veranlassen", ["Erlaubnis geben", "selbst handeln"], "case_ending"),
    "subjective_modals": ("Er muss sehr reich sein, sagt man.", "Передай непроверенный слух, не утверждая его как факт.", "Gib ein Gerücht wieder, ohne es als Tatsache darzustellen.", "Report a rumour without presenting it as fact.", "fremde Behauptung", ["sichere Tatsache", "Pflicht"], "modal_form"),
    "adjective_declension": ("Ich spreche mit einem nette Kollegen.", "Опиши коллегу, с которым ты работаешь.", "Beschreibe den Kollegen, mit dem du arbeitest.", "Describe the colleague you work with.", "Dativ nach einem", ["Akkusativ", "Nominativ"], "case_ending"),
    "verb_prepositions": ("Ich interessiere mich an Politik.", "На знакомстве расскажи о своём интересе.", "Erzähle beim Kennenlernen von deinem Interesse.", "Talk about your interest when meeting someone.", "Interesse mit für", ["Ort mit an", "Herkunft mit aus"], "fixed_connection"),
    "noun_verb_connections": ("Wir müssen eine Entscheidung machen.", "Команда должна сегодня принять решение.", "Das Team muss heute eine Entscheidung treffen.", "The team needs to make a decision today.", "feste Verbindung", ["wörtliche Übersetzung", "Passiv"], "fixed_connection"),
    "genitive_prepositions": ("Trotz dem schlechten Wetter gehen wir raus.", "Объясни, почему мероприятие состоится несмотря на погоду.", "Erkläre, warum die Veranstaltung trotz des Wetters stattfindet.", "Explain why the event is taking place despite the weather.", "trotz mit Genitiv", ["Grund mit Dativ", "Richtung"], "case_ending"),
    "pronoun_adverbs": ("Ich warte auf das, dass der Kurs beginnt.", "Скажи одногруппнику, чего ты ждёшь.", "Sage einem Kursteilnehmer, worauf du wartest.", "Tell a classmate what you are waiting for.", "Bezug auf eine Sache", ["Bezug auf eine Person", "Richtung"], "fixed_connection"),
    "nominalization": ("Wegen die Preise steigen, sparen viele Menschen.", "Сделай фразу для отчёта более формальной.", "Formuliere einen Satz für einen Bericht formeller.", "Make a sentence more formal for a report.", "formeller Nominalstil", ["direkte Rede", "informelle Erzählung"], "case_ending"),
    "formal_email": ("Gib mir bitte einen neuen Termin.", "Клиника отменила запись. Вежливо попроси новую дату.", "Die Praxis hat deinen Termin abgesagt. Bitte höflich um einen neuen.", "The clinic cancelled your appointment. Politely request a new one.", "formelle Bitte", ["private Nachricht", "Befehl"], "register"),
    "opinion": ("Homeoffice ist gut.", "На встрече вырази мнение о Homeoffice и объясни его.", "Äußere in einer Besprechung deine Meinung zum Homeoffice und begründe sie.", "Express and justify your opinion about working from home in a meeting.", "Meinung mit Grund", ["neutrale Information", "reine Aufzählung"], "cohesion"),
    "argumentation": ("Onlinekurse sind flexibel und unpersönlich.", "В дискуссии сравни плюс и минус онлайн-курсов.", "Vergleiche in einer Diskussion Vor- und Nachteil von Onlinekursen.", "Compare one advantage and disadvantage of online courses in a discussion.", "Pro und Contra", ["nur Vorteil", "zeitliche Reihenfolge"], "cohesion"),
    "listening_attitude": ("Der Sprecher findet die Idee sicher perfekt.", "Коллега говорит: Die Idee ist zwar interessant, aber kaum realistisch. Определи позицию.", "Ein Kollege sagt: Die Idee ist zwar interessant, aber kaum realistisch. Erkenne seine Haltung.", "A colleague says: Die Idee ist zwar interessant, aber kaum realistisch. Identify the attitude.", "skeptische Haltung", ["volle Zustimmung", "Begeisterung"], "wrong_connector"),
    "spoken_narrative": ("Ich habe den Bus verpasst. Ich war spät. Alles war gut.", "Расскажи другу о трудном дне в понятной последовательности.", "Erzähle einem Freund strukturiert von einem schwierigen Tag.", "Tell a friend about a difficult day in a clear sequence.", "geordnete Erzählung", ["ungeordnete Liste", "formelle Bitte"], "cohesion"),
    "b1_final": ("Großstadt ist besser, weil ja.", "Ты участвуешь в B1-дискуссии о жизни в большом городе.", "Du nimmst an einer B1-Diskussion über das Leben in der Großstadt teil.", "You are taking part in a B1 discussion about life in a large city.", "Position mit Abwägung", ["Antwort ohne Grund", "reine Beschreibung"], "cohesion"),
}


def _localized_exercise(base: dict, ru: dict, de: dict, en: dict) -> dict:
    return {**base, "i18n": {"ru": ru, "de": de, "en": en}}


def build_b1_content(row):
    day, module, topic, pillar, title_ru, title_de, title_en, rule_ru, rule_de, rule_en, prompt_ru, prompt_de, prompt_en, answer, goal_ru, goal_de, goal_en = row
    languages = {
        "ru": {"title": title_ru, "rule": rule_ru, "objective": goal_ru, "prompt": prompt_ru},
        "de": {"title": title_de, "rule": rule_de, "objective": goal_de, "prompt": prompt_de},
        "en": {"title": title_en, "rule": rule_en, "objective": goal_en, "prompt": prompt_en},
    }
    wrong, scenario_ru, scenario_de, scenario_en, meaning, meaning_distractors, misconception = B1_TASKS[topic]
    guided_type = "error_repair" if day % 2 else "transform"
    guided_prompts = {
        "ru": f"Исправь фразу: {wrong}" if guided_type == "error_repair" else prompt_ru,
        "de": f"Korrigiere den Satz: {wrong}" if guided_type == "error_repair" else prompt_de,
        "en": f"Repair the sentence: {wrong}" if guided_type == "error_repair" else prompt_en,
    }
    guided = _localized_exercise(
        {"type": guided_type, "stage": "guided", "question": guided_prompts["ru"], "answer": answer, "accepted_answers": [answer, answer.rstrip(".?!")], "hint": rule_ru, "explanation": rule_ru, "misconception": misconception},
        {"question": guided_prompts["ru"], "hint": rule_ru, "explanation": rule_ru},
        {"question": guided_prompts["de"], "hint": rule_de, "explanation": rule_de},
        {"question": guided_prompts["en"], "hint": rule_en, "explanation": rule_en},
    )
    context_options = list(dict.fromkeys([answer, wrong, f"{answer.rstrip('.?!')} nicht."]))
    patterns = [word.casefold().strip(".,?!") for word in answer.split() if len(word) > 3][:4]
    exercises = [
        guided,
        _localized_exercise(
            {"type": "context_choice", "stage": "independent", "question": scenario_ru, "answer": answer, "accepted_answers": [answer], "options": context_options, "hint": "Выбери фразу, которая и по смыслу, и по форме подходит ситуации.", "explanation": rule_ru, "misconception": misconception},
            {"question": scenario_ru, "hint": "Проверь смысл и форму.", "explanation": rule_ru},
            {"question": scenario_de, "hint": "Prüfe Bedeutung und Form.", "explanation": rule_de},
            {"question": scenario_en, "hint": "Check both meaning and form.", "explanation": rule_en},
        ),
        _localized_exercise(
            {"type": "listening_choice", "stage": "independent", "question": "Прослушай фразу. Какую функцию она выражает?", "answer": meaning, "accepted_answers": [meaning], "options": [meaning, *meaning_distractors], "hint": "Слушай не каждое слово, а смысовую связь.", "explanation": f"{meaning}: {answer}", "misconception": misconception},
            {"question": "Прослушай фразу. Какую функцию она выражает?", "hint": "Улови смысовую связь.", "explanation": f"{meaning}: {answer}"},
            {"question": "Höre zu. Welche Funktion drückt der Satz aus?", "hint": "Achte auf die Bedeutungsbeziehung.", "explanation": f"{meaning}: {answer}"},
            {"question": "Listen. What function does the sentence express?", "hint": "Listen for the relationship in meaning.", "explanation": f"{meaning}: {answer}"},
        ),
        _localized_exercise(
            {"type": "dialogue", "stage": "transfer", "question": scenario_ru, "answer": answer, "model_answer": answer, "accepted_answers": [answer, answer.rstrip(".?!")], "target_patterns": patterns, "hint": rule_ru, "explanation": "Сравни свою реакцию с моделью.", "misconception": misconception},
            {"question": scenario_ru, "hint": rule_ru, "explanation": "Сравни свою реакцию с моделью."},
            {"question": scenario_de, "hint": rule_de, "explanation": "Vergleiche deine Reaktion mit dem Modell."},
            {"question": scenario_en, "hint": rule_en, "explanation": "Compare your response with the model."},
        ),
        _localized_exercise(
            {"type": "repeat", "stage": "transfer", "question": "Произнеси модель вслух.", "answer": answer, "accepted_answers": [answer, answer.rstrip(".?!")], "explanation": "Повтори спокойно и связно.", "misconception": misconception},
            {"question": "Произнеси модель вслух.", "explanation": "Повтори спокойно и связно."},
            {"question": "Sprich das Modell laut nach.", "explanation": "Sprich ruhig und zusammenhängend."},
            {"question": "Say the model aloud.", "explanation": "Speak calmly and connect the sentence naturally."},
        ),
    ]
    return {"day": day, "week": module, "track": "B1", "module": module, "quality_version": 4, "learning_method": "notice_build_use_reflect", "title": title_ru, "objective": goal_ru, "communication_goal": goal_ru, "rule": rule_ru, "examples": [answer, answer.rstrip(".?!"), f"Das Zielmuster lautet: {answer}"], "audio_text": answer, "cefr": "B1", "prerequisites": [], "common_mistakes": [f"❌ {wrong}", f"✅ {answer}"], "recall_prompt": "Закрой пример, назови правило и создай новую фразу.", "i18n": languages, "exercises": exercises}
